---
- name: Setup new Ubuntu installation
  hosts: localhost
  gather_facts: true 
  become: true

  roles:
    - install_packages
    - vim_install_config
    - install_chrome
    - install_virtualbox
